---
- name: add the nginx apt repo
  apt_repository: repo='ppa:nginx/stable'

- apt: name=nginx
  register: install_nginx

- name: stop the nginx started when installed
  service: name=nginx
           state=stopped
  when: install_nginx | changed

- name: remove default nginx site
  file: dest={{ item }}
        state=absent
  with_items:
    - /etc/nginx/sites-enabled/default
    - /etc/nginx/sites-available/default
    - /etc/init.d/nginx
  when: install_nginx | changed

- name: copy the nginx runit service
  copy: dest=/etc/service/
        src=../files/etc/service/nginx
        mode=744

- name: symlink runit over /etc/init.d/nginx
  file: dest=/etc/init.d/nginx
        src=/usr/bin/sv
        state=link

- copy: src=etc/nginx/conf.d/log-to-stdout.conf
        dest=/etc/nginx/conf.d/
  notify: reload nginx

